apiVersion: apps/v1
kind: Deployment
metadata:
  name: bw-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bw-test
  template:
    metadata:
      labels:
        app: bw-test
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      imagePullSecrets:
        - name: regcred-new
      containers:
      - name: bw-test
        image: registry.hub.docker.com/mailravi/nodejs_git
        ports:
        - containerPort: 3000
          name: bw-test-port
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi

